### PR TITLE
Fixed getting the active servers by group name when '--group' is given

### PR DESCRIPTION
**Pull request by subramani95**

### CODE REVIEW

**Comment by ashmastaflash** [comment]
Thanks for this @subramani95! We'll pull and test this ASAP.

**Comment by mong2** [comment]
Hi @subramani95, 

A better ruby practice will be to use the ternary operator rather than the if else statement. Please see below link for the ternary operator, http://alvinalexander.com/blog/post/ruby/examples-ruby-ternary-operator-true-false-syntax. 

Thanks 

Hana

**Comment by subramani95** [comment]
Thanks @mong2 for your comments! I have updated to use ternary operator instead of if-else statements to search for the active servers, and committed it.

**Comment by mong2** [comment]
Hi @subramani95, 

Thank you for the quick code fix. However, we would not be able to accept the merge request. We would recommend it be done by `resp = options[:group].nil? ? @api.get('/servers?state=active') : @api.get("/servers?state=active#{options[:group]}")`. I will go ahead and update the change for now. 

Thank you 

Hana

**Comment by subramani95** [comment]
Thanks Hana! I didn't do this, because ':group' need to be skipped in the next block during scan. I have proposed  a change to skip ':group' in another request.

**Pull request closed without merging**
